services:
  nginxserver:
    image: lscr.io/linuxserver/nginx:latest
    container_name: "nginxserver"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./www:/config/www
      - ./config:/config
    ports:
      - 8090:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 3306:3306